#!/usr/bin/env bash
# This script fixes the bug that is keeping your Ubuntu container's
# nginx installation from listening on port 80.

rm /etc/nginx/sites-enabled/default
cp /etc/nginx/sites-available/default /etc/nginx/sites-enabled/
service nginx start
